[bumpver]
current_version = "0.4.2b4"
version_pattern = "MAJOR.MINOR.PATCH[PYTAG][NUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"cellpy//_version.py" = [
    '__version__ = "{version}"',
]

"bumpver.toml" = [
    'current_version = "{version}"',
]

