name: cellpy
channels:
    - defaults
    - conda-forge
    - pyviz
dependencies:
    - python >=3.7
    - pip
    - numpy
    - openpyxl
    - matplotlib
    - cryptography
    - click
    - scipy
    - pandas >=1.0
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
    - ipython
    - ipywidgets
    - lmfit
    - ipykernel
    - holoviz
    - hdf5
    - pytables >=3.6.1
    - python-box
    - pytest
    - invoke
    - jupyter
    - jupyterlab

