name: test setup exe on win - DID NOT WORK
on:
  workflow_dispatch:

jobs:
  Install-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: find out where we are
        shell: cmd
        run: dir
      - name: Install AccessDatabaseEngine
        shell: powershell
        run: Start-Process -Wait -FilePath "D:\a\cellpy\cellpy\bin\AccessDatabaseEngine.exe" -ArgumentList "/S" -PassThru


