name: test setup exe on win
on:
  workflow_dispatch:

jobs:
  Install-exe:
    runs-on: windows-latest
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module accessdatabaseengine_X64.exe -Force -Verbose 

